
POST http://localhost:5000/api/wilder/2/skill/3/add
Content-Type: application/json

###
DELETE http://localhost:5000/api/wilder/1/skill/2/delete
Content-Type: application/json

###
POST http://localhost:5000/api/wilder
Content-Type: application/json

{"name": "Maddie", "city":"Lyon", "email":"maddie@email.fr"}

###

GET http://localhost:5000/api/wilder

###

PUT http://localhost:5000/api/wilder/1
Content-Type: application/json

{"name":"jane doe"}

###

DELETE http://localhost:5000/api/wilder/2